#!/usr/bin/env bash
# new Env("MIUI-Auto-Task 环境配置")
echo "在本任务运行完后请不要忘记禁用该任务！"
echo "在本任务运行完后请不要忘记禁用该任务！"
echo "在本任务运行完后请不要忘记禁用该任务！"
echo "————————————"
ROOT_DIR="$(cd "$(dirname "$0")" || exit 1; pwd)"
CONFIG_DIR="$ROOT_DIR/data"
echo "开始安装依赖"
pip install -i https://mirrors.aliyun.com/pypi/simple/ -r "${ROOT_DIR}/requirements.txt"
echo "依赖已安装完毕"
echo "————————————"
echo "开始首次执行"
task "${ROOT_DIR}/miuitask.py"
echo "首次执行完毕"
echo "————————————"
echo "请不要忘记禁用该任务！"
echo "请不要忘记禁用该任务！"
echo "请不要忘记禁用该任务！"
echo "请到 ${CONFIG_DIR} 目录下的 config.yaml 或 config.yml 中配置参数 (支持 two_captcha_api_key 等新字段)"
echo "————————————"
